using System.Text;
using RegexCraft.Core.Models;

namespace RegexCraft.Core.Codegen;

/// <summary>
/// Generates idiomatic regex snippets for major languages.
/// Snippets respect engine semantics where the target language maps cleanly
/// (.NET → C#, PCRE-like → JS/Python/PHP/Java/Go/Rust notes).
/// </summary>
public sealed class CodeGenerationService : ICodeGenerationService
{
    public IReadOnlyList<CodeLanguage> SupportedLanguages { get; } =
    [
        CodeLanguage.CSharp,
        CodeLanguage.JavaScript,
        CodeLanguage.TypeScript,
        CodeLanguage.Python,
        CodeLanguage.Php,
        CodeLanguage.Java,
        CodeLanguage.Go,
        CodeLanguage.Rust,
        CodeLanguage.Ruby,
        CodeLanguage.Perl,
        CodeLanguage.Kotlin,
        CodeLanguage.Swift,
    ];

    public string Generate(
        CodeLanguage language,
        CodegenOperation operation,
        string pattern,
        string subject,
        string? replacement,
        RegexOptionsEx options,
        string engineId)
    {
        pattern ??= string.Empty;
        subject ??= string.Empty;
        replacement ??= string.Empty;
        engineId ??= "dotnet";

        var body = language switch
        {
            CodeLanguage.CSharp => GenerateCSharp(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.JavaScript => GenerateJavaScript(operation, pattern, subject, replacement, options, engineId, typescript: false),
            CodeLanguage.TypeScript => GenerateJavaScript(operation, pattern, subject, replacement, options, engineId, typescript: true),
            CodeLanguage.Python => GeneratePython(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.Php => GeneratePhp(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.Java => GenerateJava(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.Go => GenerateGo(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.Rust => GenerateRust(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.Ruby => GenerateRuby(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.Perl => GeneratePerl(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.Kotlin => GenerateKotlin(operation, pattern, subject, replacement, options, engineId),
            CodeLanguage.Swift => GenerateSwift(operation, pattern, subject, replacement, options, engineId),
            _ => $"// Unsupported language: {language}\n",
        };

        return body;
    }

    private static string EngineNoteLine(string engineId, string languageLabel, string commentPrefix = "//")
    {
        var engine = engineId.ToLowerInvariant() switch
        {
            "pcre2" => "PCRE2",
            "javascript" => "JavaScript (Jint)",
            _ => ".NET",
        };
        return $"{commentPrefix} Source engine in RegexCraft: {engine} — review {languageLabel} dialect differences before shipping.";
    }

    private static string GenerateCSharp(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by RegexCraft — System.Text.RegularExpressions (.NET)");
        if (!string.Equals(engineId, "dotnet", StringComparison.OrdinalIgnoreCase))
            sb.AppendLine("// Note: pattern was authored against PCRE2; .NET may differ on lookarounds / recursion.");
        sb.AppendLine("using System.Text.RegularExpressions;");
        sb.AppendLine();
        var opt = CSharpOptions(options);
        sb.AppendLine($"var pattern = {CsString(pattern)};");
        sb.AppendLine($"var subject = {CsString(subject)};");
        sb.AppendLine($"var options = {opt};");
        sb.AppendLine("// MatchTimeout guards against catastrophic backtracking.");
        sb.AppendLine("var regex = new Regex(pattern, options, TimeSpan.FromSeconds(2));");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("bool found = regex.IsMatch(subject);");
                sb.AppendLine("Console.WriteLine(found);");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("Match match = regex.Match(subject);");
                sb.AppendLine("if (match.Success)");
                sb.AppendLine("{");
                sb.AppendLine("    Console.WriteLine(match.Value);");
                sb.AppendLine("    // Numbered: match.Groups[1].Value");
                sb.AppendLine("    // Named:    match.Groups[\"name\"].Value");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("foreach (Match match in regex.Matches(subject))");
                sb.AppendLine("{");
                sb.AppendLine("    Console.WriteLine($\"{match.Index}: {match.Value}\");");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"var replacement = {CsString(replacement)};");
                sb.AppendLine("// Supports $1, ${name}, $&, $`, $' substitution patterns.");
                sb.AppendLine("string result = regex.Replace(subject, replacement);");
                sb.AppendLine("Console.WriteLine(result);");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("string[] parts = regex.Split(subject);");
                sb.AppendLine("foreach (var part in parts)");
                sb.AppendLine("    Console.WriteLine(part);");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string CSharpOptions(RegexOptionsEx o)
    {
        var parts = new List<string>();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) parts.Add("RegexOptions.IgnoreCase");
        if (o.HasFlag(RegexOptionsEx.Multiline)) parts.Add("RegexOptions.Multiline");
        if (o.HasFlag(RegexOptionsEx.Singleline)) parts.Add("RegexOptions.Singleline");
        if (o.HasFlag(RegexOptionsEx.ExplicitCapture)) parts.Add("RegexOptions.ExplicitCapture");
        if (o.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) parts.Add("RegexOptions.IgnorePatternWhitespace");
        return parts.Count == 0 ? "RegexOptions.None" : string.Join(" | ", parts);
    }

    private static string GenerateJavaScript(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId,
        bool typescript)
    {
        var flags = JsFlags(options);
        var sb = new StringBuilder();
        if (typescript)
        {
            sb.AppendLine("// Generated by RegexCraft — TypeScript RegExp (ECMAScript)");
            sb.AppendLine(EngineNoteLine(engineId, "TypeScript/ECMAScript"));
        }
        else
        {
            sb.AppendLine("// Generated by RegexCraft — JavaScript RegExp (ECMAScript)");
            sb.AppendLine(EngineNoteLine(engineId, "ECMAScript"));
        }

        sb.AppendLine("// Note: lookbehind / named groups need modern engines (ES2018+).");
        var decl = typescript ? "const" : "const";
        sb.AppendLine($"{decl} pattern = {JsString(pattern)};");
        sb.AppendLine($"{decl} subject = {JsString(subject)};");
        if (typescript)
            sb.AppendLine($"const regex: RegExp = new RegExp(pattern, {JsString(flags)});");
        else
            sb.AppendLine($"const regex = new RegExp(pattern, {JsString(flags)});");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("const found = regex.test(subject);");
                sb.AppendLine("console.log(found);");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("const match = subject.match(regex);");
                sb.AppendLine("if (match) {");
                sb.AppendLine("  console.log(match[0]);");
                sb.AppendLine("  // Numbered groups: match[1]");
                sb.AppendLine("  // Named groups:   match.groups?.name");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Matches:
                var gFlags = flags.Contains('g') ? flags : flags + "g";
                sb.AppendLine($"const globalRegex = new RegExp(pattern, {JsString(gFlags)});");
                sb.AppendLine("for (const match of subject.matchAll(globalRegex)) {");
                sb.AppendLine("  console.log(match.index, match[0]);");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"const replacement = {JsString(replacement)};");
                sb.AppendLine("// $1 / $& style replacements; named groups: $<name> (modern engines).");
                sb.AppendLine("const result = subject.replace(regex, replacement);");
                sb.AppendLine("console.log(result);");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("const parts = subject.split(regex);");
                sb.AppendLine("console.log(parts);");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string JsFlags(RegexOptionsEx o)
    {
        var f = new StringBuilder();
        // Prefer global for replace-all style snippets when Matches/Replace
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) f.Append('i');
        if (o.HasFlag(RegexOptionsEx.Multiline)) f.Append('m');
        if (o.HasFlag(RegexOptionsEx.Singleline)) f.Append('s');
        // Always add g for replace/matches friendliness is handled per-op; base may include g
        if (f.Length == 0)
            return "g"; // default global for practical snippets
        if (!f.ToString().Contains('g'))
            f.Append('g');
        return f.ToString();
    }

    private static string GeneratePython(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by RegexCraft — Python re module");
        sb.AppendLine(EngineNoteLine(engineId, "Python re", "#"));
        sb.AppendLine("# For full PCRE-like features consider the third-party `regex` package.");
        sb.AppendLine("import re");
        sb.AppendLine();
        sb.AppendLine($"pattern = {PyString(pattern)}");
        sb.AppendLine($"subject = {PyString(subject)}");
        var flags = PyFlags(options);
        sb.AppendLine($"flags = {flags}");
        sb.AppendLine("regex = re.compile(pattern, flags)");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("found = regex.search(subject) is not None");
                sb.AppendLine("print(found)");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("match = regex.search(subject)");
                sb.AppendLine("if match:");
                sb.AppendLine("    print(match.group(0))");
                sb.AppendLine("    # Numbered: match.group(1)");
                sb.AppendLine("    # Named:    match.group('name')");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("for match in regex.finditer(subject):");
                sb.AppendLine("    print(match.start(), match.group(0))");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"replacement = {PyString(replacement)}");
                sb.AppendLine("# Backrefs: \\1 or \\g<name>");
                sb.AppendLine("result = regex.sub(replacement, subject)");
                sb.AppendLine("print(result)");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("parts = regex.split(subject)");
                sb.AppendLine("print(parts)");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string PyFlags(RegexOptionsEx o)
    {
        var parts = new List<string>();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) parts.Add("re.IGNORECASE");
        if (o.HasFlag(RegexOptionsEx.Multiline)) parts.Add("re.MULTILINE");
        if (o.HasFlag(RegexOptionsEx.Singleline)) parts.Add("re.DOTALL");
        if (o.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) parts.Add("re.VERBOSE");
        return parts.Count == 0 ? "0" : string.Join(" | ", parts);
    }

    private static string GeneratePhp(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var delimPattern = PhpRegexLiteral(pattern, options);
        var sb = new StringBuilder();
        sb.AppendLine("<?php");
        sb.AppendLine("// Generated by RegexCraft — PHP PCRE (preg_*)");
        sb.AppendLine(EngineNoteLine(engineId, "PCRE/preg"));
        sb.AppendLine($"$pattern = {PhpString(delimPattern)};");
        sb.AppendLine($"$subject = {PhpString(subject)};");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("$found = preg_match($pattern, $subject) === 1;");
                sb.AppendLine("var_export($found);");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("if (preg_match($pattern, $subject, $matches)) {");
                sb.AppendLine("    echo $matches[0], PHP_EOL;");
                sb.AppendLine("    // Numbered: $matches[1]");
                sb.AppendLine("    // Named:    $matches['name']");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("if (preg_match_all($pattern, $subject, $matches, PREG_SET_ORDER | PREG_OFFSET_CAPTURE)) {");
                sb.AppendLine("    foreach ($matches as $match) {");
                sb.AppendLine("        echo $match[0][1], ': ', $match[0][0], PHP_EOL;");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"$replacement = {PhpString(replacement)};");
                sb.AppendLine("// $1 / ${name} style replacements in PCRE.");
                sb.AppendLine("$result = preg_replace($pattern, $replacement, $subject);");
                sb.AppendLine("echo $result, PHP_EOL;");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("$parts = preg_split($pattern, $subject);");
                sb.AppendLine("print_r($parts);");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string PhpRegexLiteral(string pattern, RegexOptionsEx options)
    {
        var flags = new StringBuilder();
        if (options.HasFlag(RegexOptionsEx.IgnoreCase)) flags.Append('i');
        if (options.HasFlag(RegexOptionsEx.Multiline)) flags.Append('m');
        if (options.HasFlag(RegexOptionsEx.Singleline)) flags.Append('s');
        if (options.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) flags.Append('x');
        // Use ~ delimiter to reduce escaping of /
        var body = pattern.Replace("~", "\\~", StringComparison.Ordinal);
        return $"~{body}~{flags}";
    }

    private static string GenerateJava(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by RegexCraft — java.util.regex");
        sb.AppendLine(EngineNoteLine(engineId, "Java Pattern"));
        sb.AppendLine("import java.util.regex.Matcher;");
        sb.AppendLine("import java.util.regex.Pattern;");
        sb.AppendLine();
        sb.AppendLine($"String pattern = {JavaString(pattern)};");
        sb.AppendLine($"String subject = {JavaString(subject)};");
        var flags = JavaFlags(options);
        if (flags != "0")
            sb.AppendLine($"Pattern regex = Pattern.compile(pattern, {flags});");
        else
            sb.AppendLine("Pattern regex = Pattern.compile(pattern);");
        sb.AppendLine("Matcher matcher = regex.matcher(subject);");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("boolean found = matcher.find();");
                sb.AppendLine("System.out.println(found);");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("if (matcher.find()) {");
                sb.AppendLine("    System.out.println(matcher.group());");
                sb.AppendLine("    // Numbered: matcher.group(1)");
                sb.AppendLine("    // Named:    matcher.group(\"name\")");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("while (matcher.find()) {");
                sb.AppendLine("    System.out.println(matcher.start() + \": \" + matcher.group());");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"String replacement = {JavaString(replacement)};");
                sb.AppendLine("// $1 / ${name} replacement syntax.");
                sb.AppendLine("String result = matcher.replaceAll(replacement);");
                sb.AppendLine("System.out.println(result);");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("String[] parts = regex.split(subject);");
                sb.AppendLine("for (String part : parts) {");
                sb.AppendLine("    System.out.println(part);");
                sb.AppendLine("}");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string JavaFlags(RegexOptionsEx o)
    {
        var parts = new List<string>();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) parts.Add("Pattern.CASE_INSENSITIVE");
        if (o.HasFlag(RegexOptionsEx.Multiline)) parts.Add("Pattern.MULTILINE");
        if (o.HasFlag(RegexOptionsEx.Singleline)) parts.Add("Pattern.DOTALL");
        if (o.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) parts.Add("Pattern.COMMENTS");
        return parts.Count == 0 ? "0" : string.Join(" | ", parts);
    }

    private static string GenerateGo(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by RegexCraft — Go regexp (RE2)");
        sb.AppendLine(EngineNoteLine(engineId, "RE2"));
        sb.AppendLine("// Engine-specific: RE2 has no lookbehind, backreferences, or recursion.");
        sb.AppendLine("package main");
        sb.AppendLine();
        sb.AppendLine("import (");
        sb.AppendLine("\t\"fmt\"");
        sb.AppendLine("\t\"regexp\"");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("func main() {");
        // Go RE2 doesn't support lookaround; still emit pattern as-is with note.
        var goPattern = GoInlineFlags(pattern, options);
        sb.AppendLine($"\tpattern := {GoString(goPattern)}");
        sb.AppendLine($"\tsubject := {GoString(subject)}");
        sb.AppendLine("\tregex := regexp.MustCompile(pattern)");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("\tfound := regex.MatchString(subject)");
                sb.AppendLine("\tfmt.Println(found)");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("\tmatch := regex.FindStringSubmatch(subject)");
                sb.AppendLine("\tif match != nil {");
                sb.AppendLine("\t\tfmt.Println(match[0])");
                sb.AppendLine("\t\t// Submatches: match[1], …");
                sb.AppendLine("\t}");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("\tfor _, match := range regex.FindAllString(subject, -1) {");
                sb.AppendLine("\t\tfmt.Println(match)");
                sb.AppendLine("\t}");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"\treplacement := {GoString(replacement)}");
                sb.AppendLine("\t// $1-style expansions in replacement.");
                sb.AppendLine("\tresult := regex.ReplaceAllString(subject, replacement)");
                sb.AppendLine("\tfmt.Println(result)");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("\tparts := regex.Split(subject, -1)");
                sb.AppendLine("\tfor _, part := range parts {");
                sb.AppendLine("\t\tfmt.Println(part)");
                sb.AppendLine("\t}");
                break;
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GoInlineFlags(string pattern, RegexOptionsEx o)
    {
        var flags = new StringBuilder();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) flags.Append('i');
        if (o.HasFlag(RegexOptionsEx.Multiline)) flags.Append('m');
        if (o.HasFlag(RegexOptionsEx.Singleline)) flags.Append('s');
        if (flags.Length == 0)
            return pattern;
        return $"(?{flags}){pattern}";
    }

    private static string GenerateRust(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by RegexCraft — Rust `regex` crate (RE2-like)");
        sb.AppendLine(EngineNoteLine(engineId, "Rust regex"));
        sb.AppendLine("// Engine-specific: no lookaround or backreferences (use fancy-regex if needed).");
        sb.AppendLine("// Cargo.toml: regex = \"1\"");
        sb.AppendLine("use regex::Regex;");
        sb.AppendLine();
        sb.AppendLine("fn main() {");
        var rustPattern = RustInlineFlags(pattern, options);
        sb.AppendLine($"    let pattern = {RustString(rustPattern)};");
        sb.AppendLine($"    let subject = {RustString(subject)};");
        sb.AppendLine("    let regex = Regex::new(pattern).expect(\"invalid pattern\");");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("    let found = regex.is_match(subject);");
                sb.AppendLine("    println!(\"{found}\");");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("    if let Some(m) = regex.find(subject) {");
                sb.AppendLine("        println!(\"{}\", m.as_str());");
                sb.AppendLine("    }");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("    for m in regex.find_iter(subject) {");
                sb.AppendLine("        println!(\"{}: {}\", m.start(), m.as_str());");
                sb.AppendLine("    }");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"    let replacement = {RustString(replacement)};");
                sb.AppendLine("    // $1 / $name style replacements.");
                sb.AppendLine("    let result = regex.replace_all(subject, replacement);");
                sb.AppendLine("    println!(\"{result}\");");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("    for part in regex.split(subject) {");
                sb.AppendLine("        println!(\"{part}\");");
                sb.AppendLine("    }");
                break;
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string RustInlineFlags(string pattern, RegexOptionsEx o)
    {
        var flags = new StringBuilder();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) flags.Append('i');
        if (o.HasFlag(RegexOptionsEx.Multiline)) flags.Append('m');
        if (o.HasFlag(RegexOptionsEx.Singleline)) flags.Append('s');
        if (o.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) flags.Append('x');
        if (flags.Length == 0)
            return pattern;
        return $"(?{flags}){pattern}";
    }

    private static string GenerateRuby(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by RegexCraft — Ruby Regexp");
        sb.AppendLine(EngineNoteLine(engineId, "Ruby Onigmo", "#"));
        var flags = RubyFlags(options);
        sb.AppendLine($"pattern = {RubyString(pattern)}");
        sb.AppendLine($"subject = {RubyString(subject)}");
        sb.AppendLine(flags.Length == 0
            ? "regex = Regexp.new(pattern)"
            : $"regex = Regexp.new(pattern, {flags})");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("found = !!(subject =~ regex)");
                sb.AppendLine("puts found");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("if (match = regex.match(subject))");
                sb.AppendLine("  puts match[0]");
                sb.AppendLine("  # Numbered: match[1]");
                sb.AppendLine("  # Named:    match[:name]");
                sb.AppendLine("end");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("subject.scan(regex) do |m|");
                sb.AppendLine("  # block yields captures; use Regexp.last_match for MatchData");
                sb.AppendLine("  puts Regexp.last_match[0]");
                sb.AppendLine("end");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"replacement = {RubyString(replacement)}");
                sb.AppendLine("# \\1 / \\k<name> style replacements");
                sb.AppendLine("result = subject.gsub(regex, replacement)");
                sb.AppendLine("puts result");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("parts = subject.split(regex)");
                sb.AppendLine("puts parts.inspect");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string RubyFlags(RegexOptionsEx o)
    {
        var parts = new List<string>();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) parts.Add("Regexp::IGNORECASE");
        if (o.HasFlag(RegexOptionsEx.Multiline)) parts.Add("Regexp::MULTILINE");
        // Ruby has no singleline equivalent exactly like DOTALL; EXTENDED for x
        if (o.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) parts.Add("Regexp::EXTENDED");
        return string.Join(" | ", parts);
    }

    private static string GeneratePerl(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var flags = PerlFlags(options);
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by RegexCraft — Perl");
        sb.AppendLine(EngineNoteLine(engineId, "Perl", "#"));
        sb.AppendLine($"my $pattern = {PerlString(pattern)};");
        sb.AppendLine($"my $subject = {PerlString(subject)};");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine($"my $found = $subject =~ /$pattern/{flags} ? 1 : 0;");
                sb.AppendLine("print $found ? \"true\\n\" : \"false\\n\";");
                break;
            case CodegenOperation.Match:
                sb.AppendLine($"if ($subject =~ /$pattern/{flags}) {{");
                sb.AppendLine("    print \"$&\\n\";");
                sb.AppendLine("    # Numbered: $1");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine($"while ($subject =~ /$pattern/{flags}g) {{");
                sb.AppendLine("    print \"$&\\n\";");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"my $replacement = {PerlString(replacement)};");
                sb.AppendLine($"$subject =~ s/$pattern/$replacement/{flags}g;");
                sb.AppendLine("print \"$subject\\n\";");
                break;
            case CodegenOperation.Split:
                sb.AppendLine($"my @parts = split /$pattern/{flags}, $subject;");
                sb.AppendLine("print \"$_\\n\" for @parts;");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string PerlFlags(RegexOptionsEx o)
    {
        var f = new StringBuilder();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) f.Append('i');
        if (o.HasFlag(RegexOptionsEx.Multiline)) f.Append('m');
        if (o.HasFlag(RegexOptionsEx.Singleline)) f.Append('s');
        if (o.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) f.Append('x');
        return f.ToString();
    }

    private static string GenerateKotlin(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by RegexCraft — Kotlin (JVM Regex)");
        sb.AppendLine(EngineNoteLine(engineId, "Kotlin/JVM"));
        sb.AppendLine($"val pattern = {JavaString(pattern)}");
        sb.AppendLine($"val subject = {JavaString(subject)}");
        var opts = KotlinOptions(options);
        if (opts == "setOf()")
            sb.AppendLine("val regex = Regex(pattern)");
        else
            sb.AppendLine($"val regex = Regex(pattern, {opts})");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("val found = regex.containsMatchIn(subject)");
                sb.AppendLine("println(found)");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("val match = regex.find(subject)");
                sb.AppendLine("if (match != null) {");
                sb.AppendLine("    println(match.value)");
                sb.AppendLine("    // Numbered: match.groupValues[1]");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("for (match in regex.findAll(subject)) {");
                sb.AppendLine("    println(\"${match.range.first}: ${match.value}\")");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"val replacement = {JavaString(replacement)}");
                sb.AppendLine("// $1 style replacements");
                sb.AppendLine("val result = regex.replace(subject, replacement)");
                sb.AppendLine("println(result)");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("val parts = regex.split(subject)");
                sb.AppendLine("parts.forEach { println(it) }");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string KotlinOptions(RegexOptionsEx o)
    {
        var parts = new List<string>();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) parts.Add("RegexOption.IGNORE_CASE");
        if (o.HasFlag(RegexOptionsEx.Multiline)) parts.Add("RegexOption.MULTILINE");
        if (o.HasFlag(RegexOptionsEx.Singleline)) parts.Add("RegexOption.DOT_MATCHES_ALL");
        if (o.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) parts.Add("RegexOption.COMMENTS");
        return parts.Count == 0 ? "setOf()" : "setOf(" + string.Join(", ", parts) + ")";
    }

    private static string GenerateSwift(
        CodegenOperation op, string pattern, string subject, string replacement, RegexOptionsEx options, string engineId)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by RegexCraft — Swift Regex");
        sb.AppendLine(EngineNoteLine(engineId, "Swift Regex / ICU"));
        sb.AppendLine("import Foundation");
        sb.AppendLine();
        sb.AppendLine($"let pattern = {JavaString(pattern)}");
        sb.AppendLine($"let subject = {JavaString(subject)}");
        var opts = SwiftOptions(options);
        sb.AppendLine($"let regex = try! NSRegularExpression(pattern: pattern, options: [{opts}])");
        sb.AppendLine("let range = NSRange(subject.startIndex..., in: subject)");
        sb.AppendLine();

        switch (op)
        {
            case CodegenOperation.IsMatch:
                sb.AppendLine("let found = regex.firstMatch(in: subject, options: [], range: range) != nil");
                sb.AppendLine("print(found)");
                break;
            case CodegenOperation.Match:
                sb.AppendLine("if let match = regex.firstMatch(in: subject, options: [], range: range),");
                sb.AppendLine("   let swiftRange = Range(match.range, in: subject) {");
                sb.AppendLine("    print(subject[swiftRange])");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Matches:
                sb.AppendLine("for match in regex.matches(in: subject, options: [], range: range) {");
                sb.AppendLine("    if let r = Range(match.range, in: subject) {");
                sb.AppendLine("        print(subject[r])");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                break;
            case CodegenOperation.Replace:
                sb.AppendLine($"let replacement = {JavaString(replacement)}");
                sb.AppendLine("// $1 style template replacements");
                sb.AppendLine("let result = regex.stringByReplacingMatches(in: subject, options: [], range: range, withTemplate: replacement)");
                sb.AppendLine("print(result)");
                break;
            case CodegenOperation.Split:
                sb.AppendLine("// NSRegularExpression has no built-in split; use matches to split manually if needed.");
                sb.AppendLine("print(subject)");
                break;
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string SwiftOptions(RegexOptionsEx o)
    {
        var parts = new List<string>();
        if (o.HasFlag(RegexOptionsEx.IgnoreCase)) parts.Add(".caseInsensitive");
        if (o.HasFlag(RegexOptionsEx.Multiline)) parts.Add(".anchorsMatchLines");
        if (o.HasFlag(RegexOptionsEx.Singleline)) parts.Add(".dotMatchesLineSeparators");
        if (o.HasFlag(RegexOptionsEx.IgnorePatternWhitespace)) parts.Add(".allowCommentsAndWhitespace");
        return parts.Count == 0 ? "" : string.Join(", ", parts);
    }

    // ── string literals ──────────────────────────────────────────────

    private static string RubyString(string s)
    {
        if (!s.Contains('\'') && !s.Contains('\\'))
            return "'" + s + "'";
        var escaped = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("#", "\\#", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }

    private static string PerlString(string s)
    {
        var escaped = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("'", "\\'", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return $"'{escaped}'";
    }


    private static string CsString(string s) =>
        "@\"" + s.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";

    private static string JsString(string s)
    {
        var escaped = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }

    private static string PyString(string s)
    {
        // Prefer triple-quoted raw when possible
        if (!s.Contains("'''", StringComparison.Ordinal) && (s.Contains('\\') || s.Contains('\n')))
            return "r'''" + s + "'''";
        var escaped = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }

    private static string PhpString(string s)
    {
        var escaped = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("$", "\\$", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }

    private static string JavaString(string s)
    {
        var escaped = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }

    private static string GoString(string s)
    {
        var escaped = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }

    private static string RustString(string s)
    {
        // raw string if no " inside
        if (!s.Contains('"') && !s.Contains('\r'))
            return "r#\"" + s + "\"#";
        var escaped = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }
}
